### ISSUE TITLE
Missing volumes param in docker-compose.yml

### ISSUE THREAD

**Issue by rafaelmaia8384** [arnidan/nsfw-api#43]
The correct docker-compose.yml should be the following:

```
version: "3.9"

services:
  nsfw-api:
    image: "ghcr.io/arnidan/nsfw-api:latest"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./model:/model
```
